### ISSUE TITLE
Default support for Mockito (1.8.0)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [andrewaylett/atunit#12]
```
I would be nice if mockito (http://mockito.org/) would be supported out of
the box.

I already solved it by providing an addon for atunit. It's attached as
subversion patch.
```

Original issue reported on code.google.com by `vitz.michael@googlemail.com` on 7 Aug 2009 at 6:06

Attachments:
* [atunit.patch](https://storage.googleapis.com/google-code-attachments/atunit/issue-12/comment-0/atunit.patch)

**Comment by andrewaylett** [comment]
As of commit ccce077ab6b4fa828ea6cfb3d52f009c3ae75525, this is implemented.
